import React from 'react';

const PrivacyPolicy = () => {
    return (
        <div className='w-11/12 md:w-8/12 mx-auto my-6 tracking-wider'>
            <h2 className='my-6 text-2xl text-center'>Madamtrails : Privacy Policy</h2>
            <p className='text-sm mb-6'><span className='font-semibold'>Last updated: July 15, 2023</span> <br />
                This Privacy Policy describes our policies and procedures regarding the collection, use, and disclosure of your information when you use the Service and informs you about your privacy rights and how the law protects you. We use your personal data to provide and improve the Service. By using the Service, you agree to the collection and use of information in accordance with this Privacy Policy.
            </p>
            <div className='grid gap-5'>
                <div>
                    <h3 className=' font-semibold mb-1'>Interpretation: </h3>
                    <p className='text-sm'>Words whose initial letter is capitalized have defined meanings under the following conditions. The following definitions shall have the same meaning regardless of whether they appear in singular or in plural.</p>
                </div>
                <div>
                    <h3 className=' font-semibold mb-1'>Definitions: </h3>
                    <p className='text-sm'>For the purposes of this Privacy Policy:</p>
                    <ul className='text-sm ms-6 grid gap-1 mt-2'>
                        <li className='list-disc'><span className='font-semibold'>Account</span> means a unique account created for You to access our Service or parts of our Service.</li>
                        <li className='list-disc'>Company (referred to as "the Company", "We", "Us" or "Our" in this Agreement) refers to madamtrails, Karnataka, India.</li>
                        <li className='list-disc'><span className='font-semibold'>Cookies</span> are small files that a website places on your computer, mobile device or any other device, and which contain details of your browsing history on that website among their many uses.</li>
                        <li className='list-disc'><span className='font-semibold'>Country</span> refers to: Karnataka, India</li>
                        <li className='list-disc'><span className='font-semibold'>Device</span> means any device that can access the Service such as a computer, a cellphone, or a digital tablet.</li>
                        <li className='list-disc'><span className='font-semibold'>Personal Data</span> means any information relating to an identified or identifiable individual.</li>
                        <li className='list-disc'><span className='font-semibold'>Service</span> refers to the website.</li>
                        <li className='list-disc'><span className='font-semibold'>Service Provider</span> means any natural or legal person who processes data on behalf of the Company. It refers to third-party companies or individuals employed by the Company to facilitate the Service, provide the Service on behalf of the Company, perform services related to the Service or assist the Company in analyzing how the Service is used.</li>
                        <li className='list-disc'><span className='font-semibold'>Usage Data</span> refers to data collected automatically, either generated by the use of the Service or from the Service infrastructure itself (for example, the duration of a page visit).</li>
                        <li className='list-disc'>Website refers to madamtrails, accessible from www.madamtrails.com</li>
                    </ul>
                </div>
                <div>
                    <h3 className=' font-semibold mb-1'>Types of Data Collected </h3>
                    <h3 className=' font-semibold mb-1'>Personal Information: </h3>
                    <p className='text-sm'>While using Our Service, we may ask You to provide us with certain personally identifiable information that can be used to contact or identify You. Personally identifiable information may include, but is not limited to:</p>
                    <ul className='text-sm ms-6 grid gap-1 mt-2'>
                        <li className='list-disc'>Email address</li>
                        <li className='list-disc'>First name and last name</li>
                        <li className='list-disc'>Phone number</li>
                    </ul>
                </div>
                <div>
                    <h3 className=' font-semibold mb-1'>Usage Data: </h3>
                    <p className='text-sm'>Usage Data is automatically collected when using the Service. Usage Data may include information such as Your device's Internet Protocol address (for example. IP address), browser type, browser version, the pages of our Service that You visit, the time and date of Your visit, the time spent on those pages, unique device identifiers, and other diagnostic data. When You access the Service by or through a mobile device, we may collect certain information automatically, including, but not limited to, the type of mobile device You use, your mobile device unique ID, the IP address of Your mobile device, your mobile operating system, the type of mobile Internet browser You use, unique device identifiers, and other diagnostic data.</p>
                </div>
                <div>
                    <h3 className=' font-semibold mb-1'>Use of Your Personal Data: </h3>
                    <p className='text-sm mb-2'>The Company may use Personal Data for the following purposes:</p>
                    <div className='grid gap-3 grid-cols-1'>
                        <p className='text-sm'>
                            <span className='font-semibold'>To provide and maintain our Service</span>, including to monitor the use of our Service.
                        </p>
                        <p className='text-sm'>
                            <span className='font-semibold'>To manage your account:</span> to manage your registration as a user of the Service. The personal data you provide can give you access to different functionalities of the Service that are available to you as a registered user.
                        </p>
                        <p className='text-sm'>
                            <span className='font-semibold'>For the performance of a contract:</span> the development, compliance, and undertaking of the purchase contract for the products, items, or services you have purchased or of any other contract with us through the Service.
                        </p>
                        <p className='text-sm'>
                            <span className='font-semibold'>To contact you:</span> to contact you by email, telephone calls, SMS, or other equivalent forms of electronic communication, such as automatic notifications from a mobile application concerning updates or informative communications related to the functionalities, products, or contracted services, including security updates, when necessary or reasonable for their implementation.
                        </p>
                        <p className='text-sm'>
                            <span className='font-semibold'>To provide you with news</span>
                            , special offers, and general information about other goods, services, and events which we offer that are similar to those you have already purchased or enquired about unless you have opted not to receive such information.
                        </p>
                        <p className='text-sm'>
                            <span className='font-semibold'>To manage your requests:</span> to attend and manage your requests to us.
                        </p>
                        <p className='text-sm'>
                            <span className='font-semibold'>For business transfers:</span> we may use your information to evaluate or conduct a merger, divestiture, restructuring, reorganization, dissolution, or other sale or transfer of some or all of our assets, whether as a going concern or as part of bankruptcy, liquidation, or similar proceeding, in which Personal Data held by us about our Service users is among the assets transferred.
                        </p>
                        <p className='text-sm'>
                            <span className='font-semibold'>For other purposes:</span> we may use your information for other purposes, such as data analysis, identifying usage trends, determining the effectiveness of our promotional campaigns, and to evaluate and improve our Service, products, services, marketing, and your experience.
                        </p>
                    </div>
                </div>
                <div>
                    <h3 className=' font-semibold mb-1'>We may share your personal information in the following situations: </h3>
                    <div className='grid gap-3 grid-cols-1'>
                        <p className='text-sm'>
                            <span className='font-semibold'>With Service Providers:</span> We may share your personal information with Service Providers to monitor and analyze the use of our Service, to contact you.
                        </p>
                        <p className='text-sm'>
                            <span className='font-semibold'>For business transfers:</span> We may share or transfer your personal information in connection with, or during negotiations of, any merger, sale of Company assets, financing, or acquisition of all or a portion of our business to another company.
                        </p>
                        <p className='text-sm'>
                            <span className='font-semibold'>With affiliates:</span> We may share your information with our affiliates, in which case we will require those affiliates to honor this Privacy Policy. Affiliates include our parent company and any other subsidiaries, joint venture partners, or other companies that we control or that are under common control with us.
                        </p>
                        <p className='text-sm'>
                            <span className='font-semibold'>With business partners:</span> We may share your information with our business partners to offer you certain products, services, or promotions.
                        </p>
                        <p className='text-sm'>
                            <span className='font-semibold'>With other users:</span>When you share personal information or interact in the public areas with other users, such information may be viewed by all users and may be publicly distributed outside.
                        </p>
                    </div>
                </div>
                <div>
                    <h3 className=' font-semibold mb-1'>Retention of your personal data: </h3>
                    <p className='text-sm'>The Company will retain your personal data only for as long as necessary to fulfill the purposes set out in this Privacy Policy. We will retain and use your personal data to the extent necessary to comply with our legal obligations (for example, if we are required to retain your data to comply with applicable laws), resolve disputes, and enforce our legal agreements and policies. The Company will also retain usage data for internal analysis purposes. Usage data is generally retained for a shorter period of time, except when this data is used to strengthen the security or to improve the functionality of our Service, or we are legally obligated to retain this data for longer periods.</p>
                </div>
                <div>
                    <h3 className=' font-semibold mb-1'>Transfer of your personal data: </h3>
                    <p className='text-sm'>Your information, including Personal Data, is processed at the Company's operating offices and in any other places where the parties involved in the processing are located. This means that this information may be transferred and maintained on computers located outside of your state, province, country, or other governmental jurisdiction where data protection laws may differ from those in your jurisdiction. Your consent to this Privacy Policy followed by your submission of such information represents your agreement to that transfer.</p>
                </div>
                <div>
                    <h3 className=' font-semibold mb-1'>Deleting your personal data: </h3>
                    <p className='text-sm'>You have the right to have your Personal Data erased or request that we assist you in erasing the Personal Data we have collected about you. Our Service may give you the ability to delete certain information about you within the Service. You may update, modify, or delete your information at any time by logging into your account, if you have one, and visiting the account settings section that allows you to manage your personal information. You may also contact us to request access, correct, or delete any personal information that you have provided to us. However, please note that we may need to retain certain information when we have a legal obligation or a legal basis to do so.</p>
                </div>
                <div>
                    <h3 className=' font-semibold mb-1'>Disclosure of your personal data </h3>
                    <h3 className=' font-semibold mb-1'>Business Transactions: </h3>
                    <p className='text-sm'>If the Company is involved in a merger, acquisition, or sale of assets, your Personal Data may be transferred. We will provide notice to you before your Personal Data is transferred and becomes subject to a different Privacy Policy.</p>
                </div>
                <div>
                    <h3 className=' font-semibold mb-1'>Compliance with the law: </h3>
                    <p className='text-sm'>Under certain circumstances, the Company may be required to disclose your Personal Data if required to do so by law or in response to valid requests by public authorities (example. a court or a government agency). <br />
                        Other legal requirements <br />
                        The Company may disclose your personal data in good faith when it believes that such action is necessary to:
                    </p>
                    <ul className='text-sm ms-6 grid gap-1 mt-2'>
                        <li className='list-disc'>Comply with a legal obligation</li>
                        <li className='list-disc'>Protect and defend the rights or property of the Company</li>
                        <li className='list-disc'>Prevent or investigate possible wrongdoing in connection with the Service</li>
                        <li className='list-disc'>Protect the personal safety of users of the Service or the public</li>
                        <li className='list-disc'>Protect against legal liability.</li>
                    </ul>
                </div>
                <div>
                    <h3 className=' font-semibold mb-1'>Detailed information about the processing of your personal data</h3>
                    <p className='text-sm'>The service providers we use may have access to your personal data. These external providers collect, store, use, process, and transfer information about your activity on our Service in accordance with their Privacy Policies.</p>
                </div>
                <div>
                    <h3 className=' font-semibold mb-1'>Links to other websites</h3>
                    <p className='text-sm'>Our Service may contain links to other websites that are not operated by us. If you click on a third-party link, you will be directed to that third party's site. We strongly advise you to review the Privacy Policy of every site you visit. We have no control over and assume no responsibility for the content, privacy policies, or practices of any third-party sites or services.</p>
                </div>
                <div>
                    <h3 className=' font-semibold mb-1'>Changes to this Privacy Policy</h3>
                    <p className='text-sm'>We may update our Privacy Policy from time to time. We will notify you of any changes by posting the new Privacy Policy on this page. We will inform you via email and/or a prominent notice on our Service, prior to the change becoming effective, and update the "Last updated" date at the top of this Privacy Policy. You are advised to review this Privacy Policy periodically for any changes. Changes to this Privacy Policy are effective when they are posted on this page.</p>
                </div>
                <div>
                    <h3 className=' font-semibold mb-1'>Contact Us: </h3>
                    <p className='text-sm'>If you have any questions about this Privacy Policy, you can contact us: <br />
                        By email: example@gmail.com <br />
                        By phone: +9798904838
                    </p>
                </div>
            </div>
        </div>
    );
};

export default PrivacyPolicy;